name: digger-classic
base: core18
summary: Classic Digger from 1983
description: |
  The remastered version of the classic Digger game 
  from 1983 for modern Linux systems for you to enjoy!
version: '1.0'
confinement: strict

apps:
  digger-classic:
    command: digger-go
    extensions: [gnome-3-28]

parts:
  digger:
    plugin: go
    go-importpath: github.com/xafero/digger-go
    source: ./digger
    go-buildtags: [ pango_1_42, gtk_3_22 ]

plugs:
  digger-home:
    interface: home
